mode: user  # NOTE: available options: [user, item]
data_path: ./data/ml-1m/ratings.dat
data_params:
  split_frac: [0.81, 0.09, 0.10]
  batch_size: 256  # NOTE: not mentioned in the paper
optim_params:
  reg_l2: 0.0  # NOTE: mentioned in the paper, but not provided
model_params:
  hidden_units: 500
  epochs: 25  # NOTE: not mentioned in the paper
