name: recsys
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python<=3.12.3
  - pip<=24.0
  - jupyter<=1.0.0
  - pandas<=2.2.2
  - polars<=0.20.21
  - pytorch<=2.2.2
  - pytorch-cuda<=12.1
  - pyyaml<=6.0.1